config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'books' =>'books#index'
root :to => 'books#top'
get 'books/:id' => 'books#show', as: 'book'
post 'books' => 'books#create'
get 'books/:id/edit' => 'books#edit', as: 'edit_book'
get 'books/:id/show' => 'books#show', as: 'show_book'
patch 'books/:id' => 'books#update', as: 'update_book'
delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
  end

  def index
    @books = Book.all
    @book = Book.new
  end


  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save
      flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])

  end

  def top
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  def destroy
    book = Book.find(params[:id])
    if     book.destroy
      flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
    else
      render action: :index
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert-warning">
    <h2><%= model.errors.count %> error prohibited this book from being saved:</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
<%= render 'books/error_messages', model: f.object %>
<div class="field">
  <label for="book_title">Title</label>
  <%= f.text_field :title %>
</div>

<div class="field">
  <label for="book_body">Body</label>
  <%= f.text_area :body %>
</div>

<div class="actions">
  <%= f.submit 'Update Book' %>
</div>
<%= link_to "Show", "/books/#{@book.id}" %> | <%= link_to "Back", "/books" %>


<% end %>

app/views/books/index.html.erb
<% if flash[:notice] %>
      <p id="notice">
        <%= flash[:notice] %>
      </p>
    <% end %>

<h1>Books</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <% @books.each do |book| %>
    <tbody>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
            <td><%= link_to "Show", "/books/#{book.id}" %></td>
            <td><%= link_to "Edit", "/books/#{book.id}/edit" %></td>
            <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
        </tr>
    </tbody>
    <% end %>
</table>


<h2>New book</h2>
<%= form_with model:@book, url:'/books', local:true do |f| %>

<%= render 'books/error_messages', model: f.object %>

<div class="field">
<label for="book_title">Title</label>
<%= f.text_field :title %>
</div>

<div class="field">
<label for="book_title">Body</label>
<%= f.text_area :body %>
</div>

<div class="actions">
  <%= f.submit 'Create Books' %>
</div>



<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
      <p id="notice">
        <%= flash[:notice] %>
      </p>
    <% end %>

<p><strong>Title</strong>:<%= @book.title %></p>
<p><strong>Body</strong>:<%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book) %> | <%= link_to "Back", "/books" %>

app/views/books/top.html.erb
<h1>ようこそ<strong>Bookers</strong>へ!</h1>
<p>
  <strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>
<p>
  <%= link_to "Start", "/books" %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>